dat1 <- read.xlsx('../data/Figure 1 data.xlsx', fill = TRUE)
dat2 <- read.xlsx('../data//Figure 2 data.xlsx', fill = TRUE)
dat22 <- read.xlsx('../data//Figure 2 data new version.xlsx', fill = TRUE)
dat3 <- read.xlsx('../data/Figure 3 data.xlsx', fill = TRUE)
datSS <- read.xlsx('../data/Figure SS data.xlsx', fill = TRUE)
