---
title: 'Data analysis for digestate experiments'
output: pdf_document
author: Sasha D. Hafner
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

# Plots

```{r}
ggplot(dat, aes(exper, e.rel, colour = treat)) +
  geom_jitter(height = 0)
```

```{r}
ggplot(dat, aes(as.integer(factor(exper)), e.rel, colour = treat, group = interaction(treat, rep))) +
  geom_point() +
  geom_line()
```

```{r}
ggplot(dat, aes(exper, e.rel, fill = treat)) +
  geom_boxplot() +
  ylim(0, 25)
```

# Stats

Set reference to untreated cattle manure.

```{r}
dat$treat <- factor(dat$treat, levels = c('U-CM', 'CC-CM', 'D-CM'))
```

```{r}
m1 <- aov(e.rel ~ treat + exper, data = dat)
summary(m1)
summary.lm(m1)
TukeyHSD(m1, 'treat')
```

CC-CM and D-CM are clearly different.
But neither is clearly different from the reference.
Makes interpretation just a bit tricky.
Some evidence of a difference but presumably digestion pH effect is moderated by low DM, and variability was high, so power is low.

Check residuals.

```{r}
plot(m1, ask = FALSE)
```

Looks fine, no need to transform.



